# Site wide configuration

title: Palladio App Documentation
description: "Full documentation for the Palladio application developed by Humanities + Design at Stanford University. Record of software updates, bug fixes, and enhancements as well as tutorials for teaching and research with Palladio."
logo: images/palladio_sq.png
#teaser: # 400x250 px default teaser image used in image archive grid
#locale: en
url: http://hdlab.stanford.edu/palladio
#url: http://localhost:4000

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist


# Octopress configuration

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: article
page_layout: article

# Format titles with titlecase?
titlecase: true


# Site owner
owner: Humanities + Design
name: Humanities + Design
email: apps@designhumanities.org
twitter: "@hdstanford"
avatar: bio-photo.jpg # 160x160 px image for author byline


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
